# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


"""
The purpose of this python3 script is to define Exacto default parameters.
"""


"""annotate-vars"""
ANNOTATE_VARS_NUM_THREADS = 4


"""build-genome-var-graph"""
BUILD_GENOME_VAR_GRAPH_REMOVE_UNKNOWN_BASES = 'yes'
BUILD_GENOME_VAR_GRAPH_TYPE = "individual"
BUILD_GENOME_VAR_GRAPH_ONLY_VARIANT_SEQUENCES = 'no'
BUILD_GENOME_VAR_GRAPH_NUM_THREADS = 4


"""build-transcriptome-var-graph"""
BUILD_TRANSCRIPTOME_VAR_GRAPH_BATCH_SIZE = 1_000
BUILD_TRANSCRIPTOME_VAR_GRAPH_TYPE = "individual"
BUILD_TRANSCRIPTOME_VAR_GRAPH_NUM_THREADS = 4


# Per-platform defaults for parameters that depend on sequencing chemistry.
# Selected via --preset {pb, ont}. An explicit flag always wins over the preset;
# the preset only fills in values the user did not supply.
CALL_DNA_VARS_PRESETS: dict[str, dict[str, float]] = {
    "pb": {
        "expected_sequencing_error": 0.01,
        "expected_slippage_probability": 0.02,
    },
    "ont": {
        "expected_sequencing_error": 0.05,
        "expected_slippage_probability": 0.10,
    },
}


"""call-germline-dna-vars"""
CALL_GERMLINE_DNA_VARS_CHUNK_SIZE = 100_000
CALL_GERMLINE_DNA_VARS_MAX_RECORDS = 7
CALL_GERMLINE_DNA_VARS_MAX_INS_NORM_EDIT_DISTANCE = 0.5
CALL_GERMLINE_DNA_VARS_MAX_INTRACHROMOSOMAL_DISTANCE = 1_000
CALL_GERMLINE_DNA_VARS_MAX_INTRACHROMOSOMAL_DISTANCE_TAU = 2_000
CALL_GERMLINE_DNA_VARS_MAX_INTERCHROMOSOMAL_DISTANCE = 1_000
CALL_GERMLINE_DNA_VARS_MAX_SLIPPAGE_REPEAT_LENGTH = 30
CALL_GERMLINE_DNA_VARS_MIN_BASE_QUALITY = 30
CALL_GERMLINE_DNA_VARS_MIN_MAPPING_QUALITY = 4
CALL_GERMLINE_DNA_VARS_MIN_TOTAL_DEPTH = 3
CALL_GERMLINE_DNA_VARS_MIN_ALT_ALLELE_FRACTION = 0.2
CALL_GERMLINE_DNA_VARS_MIN_READS = 3
CALL_GERMLINE_DNA_VARS_MIN_SIZE_PROPORTION = 0.5
CALL_GERMLINE_DNA_VARS_EXPECTED_VARIANT_ALLELE_FRACTION = 0.5
CALL_GERMLINE_DNA_VARS_EXPECTED_MUTATION_RATE = 1e-3
CALL_GERMLINE_DNA_VARS_EXPECTED_SEQUENCING_ERROR = 0.01
CALL_GERMLINE_DNA_VARS_EXPECTED_SLIPPAGE_PROBABILITY = 0.02     # 2x sequencing error rate
CALL_GERMLINE_DNA_VARS_MAX_F1_FRACTION = 0.99
CALL_GERMLINE_DNA_VARS_MAX_FPR = 1e-6
CALL_GERMLINE_DNA_VARS_NUM_THREADS = 4


"""call-somatic-dna-vars"""
CALL_SOMATIC_DNA_VARS_CHUNK_SIZE = 100_000
CALL_SOMATIC_DNA_VARS_MAX_RECORDS = 7
CALL_SOMATIC_DNA_VARS_INFINITE_SITES_ASSUMPTION = 'yes'
CALL_SOMATIC_DNA_VARS_MAX_INS_NORM_EDIT_DISTANCE = 0.5
CALL_SOMATIC_DNA_VARS_MAX_INTRACHROMOSOMAL_DISTANCE = 1_000
CALL_SOMATIC_DNA_VARS_MAX_INTRACHROMOSOMAL_DISTANCE_TAU = 2_000
CALL_SOMATIC_DNA_VARS_MAX_INTERCHROMOSOMAL_DISTANCE = 1_000
CALL_SOMATIC_DNA_VARS_MAX_SLIPPAGE_REPEAT_LENGTH = 30
CALL_SOMATIC_DNA_VARS_MIN_BASE_QUALITY = 30
CALL_SOMATIC_DNA_VARS_MIN_MAPPING_QUALITY = 4
CALL_SOMATIC_DNA_VARS_MIN_TOTAL_DEPTH = 3
CALL_SOMATIC_DNA_VARS_MIN_ALT_ALLELE_FRACTION = 0.2
CALL_SOMATIC_DNA_VARS_MIN_READS = 3
CALL_SOMATIC_DNA_VARS_MIN_SIZE_PROPORTION = 0.5
CALL_SOMATIC_DNA_VARS_EXPECTED_VARIANT_ALLELE_FRACTION = 0.25
CALL_SOMATIC_DNA_VARS_EXPECTED_MUTATION_RATE = 1e-6
CALL_SOMATIC_DNA_VARS_EXPECTED_SEQUENCING_ERROR = 0.01
CALL_SOMATIC_DNA_VARS_EXPECTED_SLIPPAGE_PROBABILITY = 0.02      # 2x sequencing error rate
CALL_SOMATIC_DNA_VARS_MAX_F1_FRACTION = 0.99
CALL_SOMATIC_DNA_VARS_MAX_FPR = 1e-6
CALL_SOMATIC_DNA_VARS_NUM_THREADS = 4


"""call-rna-vars"""
CALL_RNA_VARS_MIN_READS = 3
CALL_RNA_VARS_MIN_MAPPING_QUALITY = 20
CALL_RNA_VARS_MIN_AVERAGE_BASE_QUALITY = 30
CALL_RNA_VARS_NUM_THREADS = 4
CALL_RNA_VARS_REFERENCE_TRANSCRIPT_SCORING_METHOD = "cosine_similarity"
CALL_RNA_VARS_REFERENCE_TRANSCRIPT_SELECTION_STRATEGY = "top_k"
CALL_RNA_VARS_REFERENCE_TRANSCRIPT_TOP_K = 1
CALL_RNA_VARS_REFERENCE_TRANSCRIPT_THRESHOLD = 0.9
CALL_RNA_VARS_CHUNK_SIZE = 10_000


"""call-peptide-vars"""
CALL_PEPTIDE_VARS_MIN_K = 8
CALL_PEPTIDE_VARS_MAX_K = 11
CALL_PEPTIDE_VARS_NUM_THREADS = 4


"""diff-kmers"""
DIFF_KMERS_MIN_K = 8
DIFF_KMERS_MAX_K = 11


"""integrate-vars"""
INTEGRATE_VARS_NUM_THREADS = 4
INTEGRATE_VARS_MAX_EXON_OFFSET = 2
INTEGRATE_VARS_MAX_TRANSCRIPT_BOUNDARY_OFFSET = 10000
INTEGRATE_VARS_MAX_INTERGENIC_DISTANCE = 100000


"""remove-unspliced-rnas"""
REMOVE_UNSPLICED_RNAS_NUM_THREADS = 4
REMOVE_UNSPLICED_RNAS_MIN_MAPPING_QUALITY = 30


"""translate"""
TRANSLATE_STRATEGY = 'longest_orf'
TRANSLATE_NUM_THREADS = 4
TRANSLATE_GZIP = 'yes'
