# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


"""
The purpose of this python3 script is to define Exacto default parameters.
"""


"""annotate-vars"""
ANNOTATE_VARS_NUM_THREADS = 4


"""build-genome-var-graph"""
BUILD_GENOME_VAR_GRAPH_REMOVE_UNKNOWN_BASES = 'yes'
BUILD_GENOME_VAR_GRAPH_TYPE = "individual"
BUILD_GENOME_VAR_GRAPH_ONLY_VARIANT_SEQUENCES = 'no'
BUILD_GENOME_VAR_GRAPH_NUM_THREADS = 4


"""build-transcriptome-var-graph"""
BUILD_TRANSCRIPTOME_VAR_GRAPH_BATCH_SIZE = 1_000
BUILD_TRANSCRIPTOME_VAR_GRAPH_TYPE = "individual"
BUILD_TRANSCRIPTOME_VAR_GRAPH_NUM_THREADS = 4


CALL_DNA_VARS_PRESETS: dict[str, dict[str, int | float]] = {
    "pb": {
        "expected_sequencing_error": 0.01,
        "expected_slippage_probability": 0.03,
        "min_reads": 4,
        "min_total_depth": 4,
    },
    "ont": {
        "expected_sequencing_error": 0.05,
        "expected_slippage_probability": 0.15,
        "min_reads": 5,
        "min_total_depth": 5,
    },
}


CLUSTER_RNA_READS_PRESETS: dict[str, dict[str, int | float]] = {
    "pb": {
        "expected_sequencing_error": 0.01,
        "expected_slippage_probability": 0.03,
        "min_reads_per_cluster": 3,
        "min_reads": 3,
        "min_total_depth": 3,
    },
    "ont": {
        "expected_sequencing_error": 0.05,
        "expected_slippage_probability": 0.15,
        "min_reads_per_cluster": 4,
        "min_reads": 4,
        "min_total_depth": 4,
    },
    "corrected": {
        "expected_sequencing_error": 0.0005,
        "expected_slippage_probability": 0.0015,
        "min_reads_per_cluster": 3,
        "min_reads": 3,
        "min_total_depth": 3,
    },
}


"""call-germline-dna-vars"""
CALL_GERMLINE_DNA_VARS_CHUNK_SIZE = 100_000
CALL_GERMLINE_DNA_VARS_MAX_RECORDS = 7
CALL_GERMLINE_DNA_VARS_MAX_INS_NORM_EDIT_DISTANCE = 0.5
CALL_GERMLINE_DNA_VARS_MAX_INTRACHROMOSOMAL_DISTANCE = 1_000
CALL_GERMLINE_DNA_VARS_MAX_SLIPPAGE_REPEAT_LENGTH = 30
CALL_GERMLINE_DNA_VARS_MIN_BASE_QUALITY = 20
CALL_GERMLINE_DNA_VARS_MIN_MAPPING_QUALITY = 4
CALL_GERMLINE_DNA_VARS_MIN_TOTAL_DEPTH = 4
CALL_GERMLINE_DNA_VARS_MIN_ALT_ALLELE_FRACTION = 0.2
CALL_GERMLINE_DNA_VARS_MIN_READS = 4
CALL_GERMLINE_DNA_VARS_MIN_SIZE_PROPORTION = 0.5
CALL_GERMLINE_DNA_VARS_EXPECTED_VARIANT_ALLELE_FRACTION = 0.5
CALL_GERMLINE_DNA_VARS_EXPECTED_MUTATION_RATE = 1e-3
CALL_GERMLINE_DNA_VARS_EXPECTED_SEQUENCING_ERROR = 0.01
CALL_GERMLINE_DNA_VARS_EXPECTED_SLIPPAGE_PROBABILITY = 0.03     # 3x sequencing error rate
CALL_GERMLINE_DNA_VARS_MAX_FPR = 1e-6
CALL_GERMLINE_DNA_VARS_MIN_TERMINAL_SOFTCLIP_LENGTH = 4
CALL_GERMLINE_DNA_VARS_BKPT_RESCUE = 'yes'
CALL_GERMLINE_DNA_VARS_BKPT_RESCUE_MIN_INS_LEN = 100
CALL_GERMLINE_DNA_VARS_BKPT_RESCUE_MAX_INS_LEN = 500
CALL_GERMLINE_DNA_VARS_BKPT_RESCUE_SEARCH_DISTANCE = 1_000
CALL_GERMLINE_DNA_VARS_BKPT_RESCUE_REALIGNMENT_GAP_OPEN_SCORE = -5
CALL_GERMLINE_DNA_VARS_BKPT_RESCUE_REALIGNMENT_GAP_EXTEND_SCORE = -1
CALL_GERMLINE_DNA_VARS_BKPT_RESCUE_REALIGNMENT_K = 19
CALL_GERMLINE_DNA_VARS_BKPT_RESCUE_REALIGNMENT_BAND_WIDTH = 100
CALL_GERMLINE_DNA_VARS_BKPT_RESCUE_REALIGNMENT_MIN_SCORE_FRACTION = 0.7
CALL_GERMLINE_DNA_VARS_BKPT_RESCUE_REALIGNMENT_MIN_QUERY_COVERAGE = 0.5
CALL_GERMLINE_DNA_VARS_BKPT_RESCUE_REALIGNMENT_MIN_SPAN_PROPORTION = 0.9
CALL_GERMLINE_DNA_VARS_POA_MATCH_SCORE = 0
CALL_GERMLINE_DNA_VARS_POA_MISMATCH_SCORE = 4
CALL_GERMLINE_DNA_VARS_POA_GAP_OPEN_SCORE = 6
CALL_GERMLINE_DNA_VARS_POA_GAP_EXTEND_SCORE = 2
CALL_GERMLINE_DNA_VARS_READ_DEPTH_MAX_MERGE_DISTANCE = 1_000
CALL_GERMLINE_DNA_VARS_MIN_HOMOPOLYMER_LEN = 4
CALL_GERMLINE_DNA_VARS_MIN_DINUCLEOTIDE_CONTEXT_LEN = 4
CALL_GERMLINE_DNA_VARS_NUM_THREADS = 4


"""call-somatic-dna-vars"""
CALL_SOMATIC_DNA_VARS_CHUNK_SIZE = 100_000
CALL_SOMATIC_DNA_VARS_MAX_RECORDS = 7
CALL_SOMATIC_DNA_VARS_INFINITE_SITES_ASSUMPTION = 'yes'
CALL_SOMATIC_DNA_VARS_MAX_INS_NORM_EDIT_DISTANCE = 0.5
CALL_SOMATIC_DNA_VARS_MAX_INTRACHROMOSOMAL_DISTANCE = 1_000
CALL_SOMATIC_DNA_VARS_MAX_SLIPPAGE_REPEAT_LENGTH = 30
CALL_SOMATIC_DNA_VARS_MIN_BASE_QUALITY = 20
CALL_SOMATIC_DNA_VARS_MIN_MAPPING_QUALITY = 4
CALL_SOMATIC_DNA_VARS_MIN_TOTAL_DEPTH = 4
CALL_SOMATIC_DNA_VARS_MIN_ALT_ALLELE_FRACTION = 0.05
CALL_SOMATIC_DNA_VARS_MIN_READS = 4
CALL_SOMATIC_DNA_VARS_MIN_SIZE_PROPORTION = 0.5
CALL_SOMATIC_DNA_VARS_EXPECTED_VARIANT_ALLELE_FRACTION = 0.25
CALL_SOMATIC_DNA_VARS_EXPECTED_MUTATION_RATE = 1e-6
CALL_SOMATIC_DNA_VARS_EXPECTED_SEQUENCING_ERROR = 0.01
CALL_SOMATIC_DNA_VARS_EXPECTED_SLIPPAGE_PROBABILITY = 0.03      # 3x sequencing error rate
CALL_SOMATIC_DNA_VARS_MAX_FPR = 1e-6
CALL_SOMATIC_DNA_VARS_MIN_TERMINAL_SOFTCLIP_LENGTH = 4
CALL_SOMATIC_DNA_VARS_BKPT_RESCUE = 'yes'
CALL_SOMATIC_DNA_VARS_BKPT_RESCUE_MIN_INS_LEN = 100
CALL_SOMATIC_DNA_VARS_BKPT_RESCUE_MAX_INS_LEN = 500
CALL_SOMATIC_DNA_VARS_BKPT_RESCUE_SEARCH_DISTANCE = 1_000
CALL_SOMATIC_DNA_VARS_BKPT_RESCUE_REALIGNMENT_GAP_OPEN_SCORE = -5
CALL_SOMATIC_DNA_VARS_BKPT_RESCUE_REALIGNMENT_GAP_EXTEND_SCORE = -1
CALL_SOMATIC_DNA_VARS_BKPT_RESCUE_REALIGNMENT_K = 19
CALL_SOMATIC_DNA_VARS_BKPT_RESCUE_REALIGNMENT_BAND_WIDTH = 100
CALL_SOMATIC_DNA_VARS_BKPT_RESCUE_REALIGNMENT_MIN_SCORE_FRACTION = 0.7
CALL_SOMATIC_DNA_VARS_BKPT_RESCUE_REALIGNMENT_MIN_QUERY_COVERAGE = 0.5
CALL_SOMATIC_DNA_VARS_BKPT_RESCUE_REALIGNMENT_MIN_SPAN_PROPORTION = 0.9
CALL_SOMATIC_DNA_VARS_POA_MATCH_SCORE = 0
CALL_SOMATIC_DNA_VARS_POA_MISMATCH_SCORE = 4
CALL_SOMATIC_DNA_VARS_POA_GAP_OPEN_SCORE = 6
CALL_SOMATIC_DNA_VARS_POA_GAP_EXTEND_SCORE = 2
CALL_SOMATIC_DNA_VARS_READ_DEPTH_MAX_MERGE_DISTANCE = 1_000
CALL_SOMATIC_DNA_VARS_MIN_HOMOPOLYMER_LEN = 4
CALL_SOMATIC_DNA_VARS_MIN_DINUCLEOTIDE_CONTEXT_LEN = 4
CALL_SOMATIC_DNA_VARS_MAX_CONTROL_READS = 0
CALL_SOMATIC_DNA_VARS_NUM_THREADS = 4


"""call-rna-transcript-vars"""
CALL_RNA_VARS_MIN_MAPPING_QUALITY = 0
CALL_RNA_VARS_MIN_TERMINAL_SOFTCLIP_LENGTH = 4
CALL_RNA_VARS_BKPT_RESCUE = 'yes'
CALL_RNA_VARS_BKPT_RESCUE_MIN_INS_LEN = 100
CALL_RNA_VARS_BKPT_RESCUE_REALIGNMENT_GAP_OPEN_SCORE = -5
CALL_RNA_VARS_BKPT_RESCUE_REALIGNMENT_GAP_EXTEND_SCORE = -1
CALL_RNA_VARS_BKPT_RESCUE_REALIGNMENT_K = 11
CALL_RNA_VARS_BKPT_RESCUE_REALIGNMENT_BAND_WIDTH = 50
CALL_RNA_VARS_BKPT_RESCUE_REALIGNMENT_MIN_SCORE_FRACTION = 0.8
CALL_RNA_VARS_BKPT_RESCUE_REALIGNMENT_MIN_QUERY_COVERAGE = 0.1
CALL_RNA_VARS_BKPT_RESCUE_REALIGNMENT_MIN_PLACED_FRACTION = 0.9
CALL_RNA_VARS_BKPT_RESCUE_REALIGNMENT_MAX_PIECES = 3
CALL_RNA_VARS_PREDICT_NONSENSE_MEDIATED_DECAY = 'yes'
CALL_RNA_VARS_TRANSLATION_STRATEGY = 'longest_orf'
CALL_RNA_VARS_START_CODONS = ['AUG']
CALL_RNA_VARS_NMD_DISTANCE_THRESHOLD = 50
CALL_RNA_VARS_DNA_VARIANT_MATCH_BUFFER = 1
CALL_RNA_VARS_NUM_THREADS = 4
CALL_RNA_VARS_CHUNK_SIZE = 10_000


"""call-peptide-vars"""
CALL_PEPTIDE_VARS_MIN_K = 8
CALL_PEPTIDE_VARS_MAX_K = 11
CALL_PEPTIDE_VARS_NUM_THREADS = 4


"""cluster-rna-reads"""
# 'cdna' for a library made by reverse transcription, 'rna' for direct RNA sequencing, which
# has no reverse transcriptase template switches to filter. Matches the Rust `analyte_type` default.
CLUSTER_RNA_READS_ANALYTE_TYPE = 'cdna'
CLUSTER_RNA_READS_REMOVE_UNSPLICED_RNAS = 'yes'
CLUSTER_RNA_READS_MAX_LOCUS_GAP = 1_000_000
CLUSTER_RNA_READS_UNSPLICED_BIN_SIZE = 100_000
CLUSTER_RNA_READS_MAX_BATCH_READS = 100_000
CLUSTER_RNA_READS_MIN_MAPPING_QUALITY = 0
CLUSTER_RNA_READS_MIN_TERMINAL_SOFTCLIP_LENGTH = 4
CLUSTER_RNA_READS_MIN_READS_PER_CLUSTER = 3
CLUSTER_RNA_READS_MAX_RECORDS = 7
CLUSTER_RNA_READS_EXPECTED_SEQUENCING_ERROR = 0.01
CLUSTER_RNA_READS_EXPECTED_SLIPPAGE_PROBABILITY = 0.03
CLUSTER_RNA_READS_MAX_FPR = 1e-6
CLUSTER_RNA_READS_MAX_SLIPPAGE_REPEAT_LENGTH = 30
CLUSTER_RNA_READS_MIN_SIZE_PROPORTION = 0.5
CLUSTER_RNA_READS_MAX_INS_NORM_EDIT_DISTANCE = 0.5
CLUSTER_RNA_READS_MAX_INTRACHROMOSOMAL_DISTANCE = 1_000
CLUSTER_RNA_READS_MEC_MAX_K = 7
CLUSTER_RNA_READS_MEC_NUM_RESTARTS = 1000
CLUSTER_RNA_READS_MEC_MAX_ITER = 10000
CLUSTER_RNA_READS_MEC_SEED = 42
CLUSTER_RNA_READS_TS_MIN_HOMOLOGY = 8
CLUSTER_RNA_READS_TS_SOFT_MIN_HOMOLOGY = 5
CLUSTER_RNA_READS_TS_MAX_BREAKPOINT_DISPERSION = 2
CLUSTER_RNA_READS_MAX_UNSPLICED_LOCUS_GAP = 0
CLUSTER_RNA_READS_CHUNK_SIZE = 10_000
CLUSTER_RNA_READS_SOFT_CLIP_REMOVAL = 'yes'
CLUSTER_RNA_READS_SOFT_CLIP_MAX_BOUNDARY_DISTANCE = 3
CLUSTER_RNA_READS_SOFT_CLIP_BASES_PER_EDIT = 8
CLUSTER_RNA_READS_SOFT_CLIP_MIN_PARTNER_BASES = 20
CLUSTER_RNA_READS_UNPLACED_TAIL_REMOVAL = 'yes'
CLUSTER_RNA_READS_UNPLACED_TAIL_MIN_INS_LEN = 100
CLUSTER_RNA_READS_BKPT_RESCUE = 'yes'
CLUSTER_RNA_READS_BKPT_RESCUE_MIN_INS_LEN = 100
CLUSTER_RNA_READS_BKPT_RESCUE_REALIGNMENT_GAP_OPEN_SCORE = -5
CLUSTER_RNA_READS_BKPT_RESCUE_REALIGNMENT_GAP_EXTEND_SCORE = -1
CLUSTER_RNA_READS_BKPT_RESCUE_REALIGNMENT_K = 11
CLUSTER_RNA_READS_BKPT_RESCUE_REALIGNMENT_BAND_WIDTH = 50
CLUSTER_RNA_READS_BKPT_RESCUE_REALIGNMENT_MIN_SCORE_FRACTION = 0.8
CLUSTER_RNA_READS_BKPT_RESCUE_REALIGNMENT_MIN_QUERY_COVERAGE = 0.1
CLUSTER_RNA_READS_BKPT_RESCUE_REALIGNMENT_MIN_PLACED_FRACTION = 0.9
CLUSTER_RNA_READS_BKPT_RESCUE_REALIGNMENT_MAX_PIECES = 3
CLUSTER_RNA_READS_POA_MATCH_SCORE = 0
CLUSTER_RNA_READS_POA_MISMATCH_SCORE = 4
CLUSTER_RNA_READS_POA_GAP_OPEN_SCORE = 6
CLUSTER_RNA_READS_POA_GAP_EXTEND_SCORE = 2
CLUSTER_RNA_READS_MIN_READS = 3
CLUSTER_RNA_READS_MIN_TOTAL_DEPTH = 3
CLUSTER_RNA_READS_MIN_HOMOPOLYMER_LEN = 4
CLUSTER_RNA_READS_MIN_DINUCLEOTIDE_CONTEXT_LEN = 4
CLUSTER_RNA_READS_TEMPLATE_SWITCH_FLANK = 20
CLUSTER_RNA_READS_TEMPLATE_SWITCH_FOLDBACK_MIN_STEM = 5
CLUSTER_RNA_READS_TEMPLATE_SWITCH_FOLDBACK_MAX_LOOP_LEN = 20
CLUSTER_RNA_READS_TEMPLATE_SWITCH_FOLDBACK_MAX_DISTANCE = 1_000
CLUSTER_RNA_READS_TEMPLATE_SWITCH_FOLDBACK_SLACK = 20
CLUSTER_RNA_READS_ALLOWED_VARIANT_MAX_DISTANCE = 10
CLUSTER_RNA_READS_NUM_THREADS = 4


"""correct-rna-reads"""
CORRECT_RNA_READS_MAX_CORRECTABLE_EVENT_LEN = 50
CORRECT_RNA_READS_CORRECTED_BASE_QUALITY = 60
CORRECT_RNA_READS_TRIM_TRANSCRIPT_ENDS = False
CORRECT_RNA_READS_NUM_THREADS = 4
CORRECT_RNA_READS_CHUNK_SIZE = 10_000


"""determine-rna-consensus"""
DETERMINE_RNA_CONSENSUS_SCORE_MATCH = 0
DETERMINE_RNA_CONSENSUS_SCORE_MISMATCH = 4
DETERMINE_RNA_CONSENSUS_SCORE_GAP_OPEN = 6
DETERMINE_RNA_CONSENSUS_SCORE_GAP_EXTEND = 2
DETERMINE_RNA_CONSENSUS_MAX_READS_PER_CLUSTER = 1000
DETERMINE_RNA_CONSENSUS_SEED = 42
DETERMINE_RNA_CONSENSUS_ORIENTATION_KMER_SIZE = 15
DETERMINE_RNA_CONSENSUS_NUM_THREADS = 4


"""integrate-vars"""
INTEGRATE_VARS_NUM_THREADS = 4
INTEGRATE_VARS_MAX_EXON_OFFSET = 2
INTEGRATE_VARS_MAX_TRANSCRIPT_BOUNDARY_OFFSET = 10000
INTEGRATE_VARS_MAX_INTERGENIC_DISTANCE = 100000


"""quantify-rna-abundances"""
QUANTIFY_RNA_ABUNDANCES_PSEUDO_COUNT = 1e-2
QUANTIFY_RNA_ABUNDANCES_MAX_ITER = 10_000
QUANTIFY_RNA_ABUNDANCES_TOL = 1e-9


"""remove-unspliced-rnas"""
REMOVE_UNSPLICED_RNAS_NUM_THREADS = 4
REMOVE_UNSPLICED_RNAS_MIN_MAPPING_QUALITY = 30


"""stitch-reference-transcripts"""
STITCH_REFERENCE_TRANSCRIPTS_MIN_MAPPING_QUALITY = 0
STITCH_REFERENCE_TRANSCRIPTS_MIN_NUM_SPLICE_JUNCTION_MATCHES = 1
STITCH_REFERENCE_TRANSCRIPTS_PAS_SEARCH_SIZE = 40
STITCH_REFERENCE_TRANSCRIPTS_PAS_HEXAMERS = ['AATAAA', 'ATTAAA']
# Inclusive (min, max), mirroring the Rust `pas_start_offset_range: 10..=40`.
STITCH_REFERENCE_TRANSCRIPTS_PAS_START_OFFSET_RANGE = (10, 40)
STITCH_REFERENCE_TRANSCRIPTS_POLYA_TAIL_MIN_ADENOSINE_FRACTION = 0.8
STITCH_REFERENCE_TRANSCRIPTS_POLYA_WINDOW_SIZE = 20
STITCH_REFERENCE_TRANSCRIPTS_POLYA_MIN_CONSECUTIVE_ADENOSINE = 6
STITCH_REFERENCE_TRANSCRIPTS_NUM_THREADS = 4


"""translate"""
TRANSLATE_STRATEGY = 'longest_orf'
TRANSLATE_START_CODONS = ['AUG']
TRANSLATE_NUM_THREADS = 4
