[package]
name = "exacto"
version.workspace = true
edition = "2021"
authors = ["Jin Seok Lee <ajslee@unc.edu>"]
rust-version.workspace = true
description = "Exacto"
homepage = "https://github.com/pirl-unc/exacto/tree/main/exacto"
repository = "https://github.com/pirl-unc/exacto/tree/main/exacto"
documentation = "https://github.com/pirl-unc/exacto"
license.workspace = true

[dependencies]
exacto-annotator = { workspace = true }
exacto-caller = { workspace = true }
exacto-core = { workspace = true }
exacto-graph = { workspace = true }
exacto-qc = { workspace = true }
exacto-integrator = { workspace = true }
exacto-translator = { workspace = true }
