sudo: false  # Use container-based infrastructure
language: python
python:
  - "3.9"
os:
  - linux
cache:
  pip: true
  directories:
  - $HOME/cache/
  - $HOME/cache/pyensembl/GRCh38/ensembl95/
  - $HOME/cache/cargo/
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  # reset the shell's lookup table for program name to path mappings
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - python --version
install:
  - >
      conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - conda config --add channels bioconda
  - conda config --add channels conda-forge
  - conda install -c conda-forge mamba
  - mamba install rust
  - mamba install pandas==1.5.2
  - mamba install numpy==1.23.1
  - mamba install pyensembl==2.1.0
  - export PYENSEMBL_CACHE_DIR=$HOME/cache/
  - pyensembl install --release 95 --species human --custom-mirror https://github.com/openvax/ensembl-data/releases/download/GRCh38.95/
  - mamba install pysam==0.19.1
  - mamba install pylint
  - mamba install maturin
  - export CARGO_TARGET_DIR=$HOME/cache/cargo/
  - export CARGO_BUILD_TARGET_DIR=$HOME/cache/cargo/
  - maturin build --release
  - conda install -c anaconda openssl
  - pip install . --ignore-installed --verbose
  - conda install -c conda-forge coveralls
  - conda install -c conda-forge nose
before_script:
  - ./lint.sh
script:
  - nosetests test --with-coverage --cover-package=exacto
after_success:
  coveralls