[package]
name = "exacto-translator"
version = "0.4.5"
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
exacto-annotator = { path = "../exacto-annotator", version = "0.4.5" }
exacto-caller = { path = "../exacto-caller", version = "0.4.5" }
exacto-core = { path = "../exacto-core", version = "0.4.5" }
flate2 = "1.0"
noodles-fastq = "0.16.0"
polars = { version = "0.45.0", features = ["csv","json","lazy","parquet","serde"] }
rayon = "1.10.0"
serde = { version = "1.0.210", features = ["derive"] }
tempfile = "3.6"

[profile.dev]
opt-level = 0

[profile.release]
incremental = true