[package]
name = "exacto-translator"
version.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
exacto-annotator = { workspace = true }
exacto-caller = { workspace = true }
exacto-core = { workspace = true }
exacto-integrator = { workspace = true }
bimap = { workspace = true }
csv = { workspace = true }
flate2 = { workspace = true }
noodles-fastq = { workspace = true }
polars = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
tempfile = { workspace = true }
