[package]
name = "exacto-annotator"
version.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
exacto-caller = { workspace = true }
exacto-core = { workspace = true }
bio = { workspace = true }
flate2 = { workspace = true }
indicatif = { workspace = true }
noodles-bgzf = { workspace = true }
noodles-fasta = { workspace = true }
once_cell = { workspace = true }
phf = { workspace = true }
polars = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
tempfile = { workspace = true }
