exacto call-rna-vars \
  --bam-file ../test/data/bam/rna-100-tumor_minimap2_mdtagged_sorted.bam \
  --bam-bai-file ../test/data/bam/rna-100-tumor_minimap2_mdtagged_sorted.bam.bai \
  --reference-genome-fasta-file ../test/data/fasta/hg38_chr17-18.fa.gz \
  --reference-gene-annotation-file ../test/data/gtf/gencode.v41.annotation.chr17-18.gtf.gz \
  --reference-gene-annotation-source gencode \
  --reference-gene-annotation-assembly hg38 \
  --reference-gene-annotation-version v41 \
  --output-dir outputs/rna-100-tumor-minimap2_mdtagged_sorted_bam_exacto_call_rna_vars_outputs/ \
  --output-prefix rna-100-tumor_minimap2_mdtagged_sorted \
  --reference-transcript-scoring-method cosine_similarity \
  --reference-transcript-selection-strategy top_k \
  --reference-transcript-top-k 3
