[workspace]
members = [
    "exacto",
    "exacto-annotator",
    "exacto-caller",
    "exacto-core",
    "exacto-graph",
    "exacto-integrator",
    "exacto-qc",
    "exacto-translator"
]
resolver = "2"

[workspace.package]
license = "MIT"
edition = "2021"
rust-version = "1.79.0"

[workspace.dependencies]
