extern crate bimap;
extern crate bstr;
extern crate chrono;
extern crate edit_distance;
extern crate env_logger;
extern crate exacto_caller;
extern crate exacto_cluster;
extern crate exacto_core;
extern crate flate2;
extern crate interavl;
extern crate indicatif;
extern crate itertools;
extern crate log;
extern crate nalgebra;
extern crate noodles_bam;
extern crate noodles_bgzf;
extern crate noodles_core;
extern crate noodles_fasta;
extern crate noodles_fastq;
extern crate noodles_sam;
extern crate once_cell;
extern crate polars;
extern crate rayon;
extern crate rand;
extern crate rand_pcg;
extern crate regex;
extern crate serde;
extern crate statrs;
extern crate sysinfo;
extern crate tempfile;
extern crate thiserror;

#[cfg(test)]
mod tests;
pub mod common;
pub mod correction;
pub mod pipeline;
pub mod prelude;
