---
title: "Variants List TSV"
---

The `convert` command in `Exacto` converts a VCF (variant call format) file to a TSV (tab-separated values) file so that variant lists can be made easier to wrangle and view (on Excel). This section describes the headers found in a variants TSV file. Please note that the tool-specific descriptions were taken from the respective software programs.

`Exacto` supports conversion to TSV for VCF files generated from the following variant callers:

- [cuteSV](#cutesv-headers)
- [DeepVariant](#deepvariant-headers)
- [Delly2](#delly2-headers)
- [GATK4-Mutect2](#gatk4-mutect2-headers)
- [LUMPY](#lumpy-headers)
- [pbsv](#pbsv-headers)
- [Sniffles2](#sniffles2-headers)
- [Strelka2-Germline](#strelka2-germline-headers)
- [Strelka2-Somatic](#strelka2-somatic-headers)
- [SVIM](#svim-headeres)

Note that the `default` value for all of the columns below is an empty string (i.e. `''`) in the converted TSV file.

### Common Headers

Listed below are the common headers present in TSV files converted from VCF files by `Exacto`. The following attributes help to define the essential information pertaining to a `DNA` or `RNA` variant identified by a caller. The attributes were selected to represent various types of variants (e.g. single-nucleotide variants, multi-nucleotide variants, insertions, deletions, inversions, translocations, fusion genes, intron retention, splice variants, endogenous retroviruses etc) concordantly identified by multiple callers. Note that RNA variants identified `Exacto` adhere to the following format. When variant lists (TSV files) are merged using the `merge` command in `Exacto`, attribute values from different callers are concatenated using commas (e.g. 'tumor_variant_reads_count' = '7,8,7' from 3 callers).

<div class="table">

| Header                               | Description                                                                                               |
| ------------------------------------ | --------------------------------------------------------------------------------------------------------- |
| source_id                            | Source ID                                                                                                 |
| tumor_sample_id                      | Tumor sample ID                                                                                           |
| normal_sample_id                     | Normal sample ID                                                                                          |
| variant_id                           | Variant ID(s)                                                                                             |
| variant_calling_method               | Variant calling method(s)                                                                                 |
| sequencing_platform                  | Sequencing platform(s)                                                                                    |
| chr_1                                | Chromosome 1                                                                                              |
| pos_1                                | Position 1 value(s)                                                                                       |
| pos_1_stdev                          | Standard deviation of position 1 value(s)                                                                 |
| chr_2                                | Chromosome 2                                                                                              |
| pos_2                                | Position 2 value(s)                                                                                       |
| pos_2_stdev                          | Standard deviation of position 2 value(s)                                                                 |
| ref                                  | Reference allele(s)                                                                                       |
| alt                                  | Alternate allele (s)                                                                                      |
| filter                               | Filter(s)                                                                                                 |
| quality_score                        | Quality score(s)                                                                                          |
| precise                              | If SV breakpoint is precise, true; otherwise, false                                                       |                     
| variant_type                         | Variant type(s)                                                                                           |
| variant_subtype                      | Variant subtype(s)                                                                                        |
| variant_size                         | Variant size(s)                                                                                           |
| variant_sequence                     | Variant sequence(s)                                                                                       |
| total_tumor_dna_reads                | Number(s) of total DNA reads in tumor                                                                     |
| ref_tumor_dna_reads                  | Number(s) of DNA reads in tumor supporting reference allele                                               |
| alt_tumor_dna_reads                  | Number(s) of DNA reads in tumor supporting alternate allele                                               |
| other_tumor_dna_reads                | Number(s) of DNA reads in tumor supporting other allele                                                   |
| alt_tumor_dna_fraction               | Tumor DNA variant allele fraction(s)                                                                      |
| total_normal_dna_reads               | Number(s) of total DNA reads in normal                                                                    |
| ref_normal_dna_reads                 | Number(s) of DNA reads in normal supporting reference allele                                              |
| alt_normal_dna_reads                 | Number(s) of DNA reads in normal supporting alternate allele                                              |
| other_normal_dna_reads               | Number(s) of DNA reads in normal supporting other allele                                                  |
| alt_normal_dna_fraction              | Normal DNA variant allele fraction(s)                                                                     |
| alt_tumor_dna_read_id                | IDs of DNA reads supporing alternate allele in tumor                                                      |
| alt_normal_dna_read_id               | IDs of DNA reads supporing alternate allele in normal                                                     |
| alt_tumor_dna_softclip_direction     | Tumor DNA variant softclipped directions                                                                  |
| alt_normal_dna_softclip_direction    | Normal DNA variant softclipped directions                                                                 |
| total_tumor_rna_reads                | Number(s) of total RNA reads in tumor                                                                     |
| ref_tumor_rna_reads                  | Number(s) of RNA reads in tumor supporting reference allele                                               |
| alt_tumor_rna_reads                  | Number(s) of RNA reads in tumor supporting alternate allele                                               |
| other_tumor_rna_reads                | Number(s) of RNA reads in tumor supporting other allele                                                   |
| alt_tumor_rna_fraction               | Tumor RNA variant allele fraction(s)                                                                      |
| total_normal_rna_reads               | Number(s) of total RNA reads in normal                                                                    |
| ref_normal_rna_reads                 | Number(s) of RNA reads in normal supporting reference allele                                              |
| alt_normal_rna_reads                 | Number(s) of RNA reads in normal supporting alternate allele                                              |
| other_normal_rna_reads               | Number(s) of RNA reads in normal supporting other allele                                                  |
| alt_normal_rna_fraction              | Normal RNA variant allele fraction(s)                                                                     |
| alt_tumor_rna_read_id                | IDs of DNA reads supporing alternate allele in tumor                                                      |
| alt_normal_rna_read_id               | IDs of DNA reads supporing alternate allele in normal                                                     |
| alt_tumor_rna_softclip_direction     | Tumor RNA variant softclipped directions                                                                  |
| alt_normal_rna_softclip_direction    | Normal RNA variant softclipped directions                                                                 |
: {tbl-colwidths="[30,55,15]"}

</div>

### DeepVariant Headers

A DeepVariant TSV includes all of the common headers. The descriptions were taken from DeepVariant 1.4.0.

<div class="table">

| Header                               | Description                                                                                               |
| ------------------------------------ | --------------------------------------------------------------------------------------------------------- |
| deepvariant_end                      | "End position (for use with symbolic alleles)" ('END' in VCF INFO)                                        |
| deepvariant_gt                       | "Genotype" ('GT' in VCF FORMAT)                                                                           |
| deepvariant_gq                       | "Conditional genotype quality" ('GQ' in VCF FORMAT)                                                       |
| deepvariant_dp                       | "Read depth" ('DP' in VCF FORMAT)                                                                         |
| deepvariant_min_dp                   | "Minimum DP observed within the GVCF block" ('MIN_DP' in VCF FORMAT)                                      |
| deepvariant_ad                       | "Read depth for each allele" ('AD' in VCF FORMAT)                                                         |
| deepvariant_vaf                      | "Variant allele fractions" ('VAF' in VCF FORMAT)                                                          |
| deepvariant_pl                       | "Phred-scaled genotype likelihoods rounded to the closest integer" ('PL' in VCF FORMAT)                   |
| deepvariant_med_dp                   | "Median DP observed within the GVCF block rounded to the nearest integer" ('MED_DP' in VCF FORMAT)        |                      
: {tbl-colwidths="[30,55,15]"}

</div>

### GATK4-Mutect2 Headers

In addition to the following GATK4-Mutect2 specific headers, a GATK4-Mutect2 VCF file converted to a TSV file includes all of the above common headers.

<div class="table">

| Header                               | Description                                                                                               |
| ------------------------------------ | --------------------------------------------------------------------------------------------------------- |
| gatk4-mutect2_as_filter_status       | "Filter status for each allele, as assessed by ApplyVQSR" ('AS_FilterStatus' in VCF INFO)                 |
| gatk4-mutect2_as_sb_table            | "Allele-specific forward/reverse read counts for strand bias tests. Includes the reference and alleles separates by \|" ('AS_SB_TABLE' in VCF INFO) |
| gatk4-mutect2_as_uniq_alt_read_count | "Number of reads with unique start and mate end positions for each alt at a variant site" ('AS_UNIQ_ALT_READ_COUNT' in VCF INFO) |
| gatk4-mutect2_contq                  | "Phred-scaled qualities that alt allele are not due to contamination" ('CONTQ' in VCF INFO) |
| gatk4-mutect2_dp                     | "Approximate read dept; som reads may have been filtered" ('DP' in VCF INFO)                |
| gatk4-mutect2_ecnt                   | "Number of events in this haplotype" ('ECNT' in VCF INFO)                                   |
| gatk4-mutect2_germq                  | "Phred-scaled quality that alt alleles are not germline variants" ('GERMQ' in VCF INFO)     |
| gatk4-mutect2_mbq                    | "Median base quality by allele" ('MBQ' in VCF INFO)                                         |
| gatk4-mutect2_mfrl                   | "Median fragment length by allele" ('MFRL' in VCF INFO)                                     |
| gatk4-mutect2_mmq                    | "Median mapping quality by allele" ('MMQ' in VCF INFO)                                      |
| gatk4-mutect2_mpos                   | "Median distance from end of read" ('MPOS' in VCF INFO)                                     |
| gatk4-mutect2_nalod                  | "Negative log 10 odds of artifact in normal with same allele fraction as tumor" ('NALOD' in VCF INFO) |
| gatk4-mutect2_ncount                 | "Count of n bases in the pileup" ('NCount' in VCF INFO)                                     |
| gatk4-mutect2_nlod                   | "Normal log 10 likelihood ratio of diploid het or hom alt genotypes" ('NLOD' in VCF INFO)   |
| gatk4-mutect2_ocm                    | "Number of alt reads whose original alignment doesn't match the current contig" ('OCM' in VCF INFO) |
| gatk4-mutect2_pon                    | "Site found in panel of normals" ('PON' in VCF INFO)                                        |
| gatk4-mutect2_popaf                  | "Negative log 10 population allele frequencies of alt alleles" ('POPAF' in VCF INFO)        |
| gatk4-mutect2_roq                    | "Phred-scaled qualities that alt allele are not due to read orientation artifact" ('ROQ' in VCF INFO) |
| gatk4-mutect2_rpa                    | "Number of times tandem repeat unit is repated, for each allele including reference" ('RPA' in VCF INFO) |
| gatk4-mutect2_ru                     | "Tandem repeat unit in bases" ('RU' in VCF INFO)                                            |
| gatk4-mutect2_seqq                   | "Phred-scaled quality that alt alleles are not sequencing errors" ('SEQQ' in VCF INFO)      |
| gatk4-mutect2_str                    | "Variant is a short tandem repeat" ('STR' in VCF INFO)                                      |
| gatk4-mutect2_strandq                | "Phred-scaled quality of strand bias artifact" ('STRANDQ' in VCF INFO)                      |
| gatk4-mutect2_strq                   | "Phred-scaled quality that alt alleles in STRs are not polymerase slippage errors" ('STRQ' in VCF INFO) |
| gatk4-mutect2_tlod                   | "Log10 likelihood ratio score of variant existing versus not existing" ('TLOD' in VCF INFO) |
| gatk4-mutect2_tumor_ad               | "Allelic depths for the ref and alt alleles in the order listed" ('AD' in VCF FORMAT)       |
| gatk4-mutect2_normal_ad              | "Allelic depths for the ref and alt alleles in the order listed" ('AD' in VCF FORMAT)       |
| gatk4-mutect2_tumor_af               | "Allele fractions of alternate alleles in the tumor" ('AF' in VCF FORMAT)                   |
| gatk4-mutect2_normal_af              | "Allele fractions of alternate alleles in the tumor" ('AF' in VCF FORMAT)                   |
| gatk4-mutect2_tumor_dp               | "Approximate read depth (reads with MQ=255 or with bad mates are filtered)" ('DP' in VCF FORMAT) |
| gatk4-mutect2_normal_dp              | "Approximate read depth (reads with MQ=255 or with bad mates are filtered)" ('DP' in VCF FORMAT) |
| gatk4-mutect2_tumor_f1r2             | "Count of reads in F1R2 pair orientation supporting each allele" ('F1R2' in VCF FORMAT)     |
| gatk4-mutect2_normal_f1r2            | "Count of reads in F1R2 pair orientation supporting each allele" ('F1R2' in VCF FORMAT)     |
| gatk4-mutect2_tumor_f2r1             | "Count of reads in F2R1 pair orientation supporting each allele" ('F2R1' in VCF FORMAT)     |
| gatk4-mutect2_normal_f2r1            | "Count of reads in F2R1 pair orientation supporting each allele" ('F2R1' in VCF FORMAT)     |
| gatk4-mutect2_tumor_fad              | "Count of fragments supporting each allele" ('FAD' in VCF FORMAT)                           |
| gatk4-mutect2_normal_fad             | "Count of fragments supporting each allele ('FAD' in VCF FORMAT)"                           |
| gatk4-mutect2_tumor_gq               | "Genotype quality" ('GQ' in VCF FORMAT)                                                     |
| gatk4-mutect2_normal_gq              | "Genotype quality" ('GQ' in VCF FORMAT)                                                     |
| gatk4-mutect2_tumor_gt               | "Genotype" ('GT' in VCF FORMAT)                                                             |
| gatk4-mutect2_normal_gt              | "Genotype" ('GT' in VCF FORMAT)                                                             |
| gatk4-mutect2_tumor_pgt              | "Physical phasing haplotype information, describing how the alternate alleles are phased in relation to one another; will always be heterozygous and is not intended to describe called alleles" ('PGT' in VCF FORMAT)                                                                          |
| gatk4-mutect2_normal_pgt             | "Physical phasing haplotype information, describing how the alternate alleles are phased in relation to one another; will always be heterozygous and is not intended to describe called alleles" ('PGT' in VCF FORMAT)                                                                           |
| gatk4-mutect2_tumor_pid              | "Physical phasing ID information, where each unique ID within a given sample (but not across samples) connects records within a phasing group" ('PID' in VCF FORMAT)                                                                                                                          |
| gatk4-mutect2_normal_pid             | "Physical phasing ID information, where each unique ID within a given sample (but not across samples) connects records within a phasing group" ('PID' in VCF FORMAT)                                                                                                                          |
| gatk4-mutect2_tumor_pl               | "Normalized, Phred-scaled likelihoods for genotypes as defined in the VCF specification" ('PL' in VCF FORMAT) |
| gatk4-mutect2_normal_pl              | "Normalized, Phred-scaled likelihoods for genotypes as defined in the VCF specification" ('PL' in VCF FORMAT) |
| gatk4-mutect2_tumor_ps               | "Phasing set (typically the position of the first variant in the set)" ('PS' in VCF FORMAT) |
| gatk4-mutect2_normal_ps              | "Phasing set (typically the position of the first variant in the set)" ('PS' in VCF FORMAT) |
| gatk4-mutect2_tumor_sb               | "Per-sample component statistics which comprise the Fisher's Exact Test to detect strand bias" ('SB' in VCF FORMAT) |
| gatk4-mutect2_normal_sb              | "Per-sample component statistics which comprise the Fisher's Exact Test to detect strand bias" ('SB' in VCF FORMAT) |
: {tbl-colwidths="[30,55,15]"}

</div>

### pbsv Headers

A pbsv TSV includes all of the common headers. The descriptions were taken from pbsv 2.8.0.

<div class="table">

| Header                               | Description                                                                                               |
| ------------------------------------ | --------------------------------------------------------------------------------------------------------- |
| pbsv_svtype                          | "Type of structural variant" ('SVTYPE' in VCF INFO)                                                       |
| pbsv_end                             | "End position of the structural variant described in this record" ('END' in VCF INFO)                     |
| pbsv_svlen                           | "Difference in length between REF and ALT alleles" ('SVLEN' in VCF INFO)                                  |
| pbsv_svann                           | "Repeat annotation of structural variant" ('SVANN' in VCF INFO)                                           |
| pbsv_cipos                           | "Confidence interval around POS for imprecise variants" ('CIPOS' in VCF INFO)                             |
| pbsv_mateid                          | "ID of mate breakends" ('MATEID' in VCF INFO)                                                             |
| pbsv_matedist                        | "Distance to the mate breakend for mates on the same contig" ('MATEDIST' in VCF INFO)                     |
| pbsv_precise                         | "Precise structural variation" ('PRECISE' in VCF INFO)                                                    |
| pbsv_gt                              | "Genotype" ('GT' in VCF FORMAT)                                                                             |
| pbsv_ad                              | "Read depth per allele" ('AD' in VCF FORMAT)                                                                |
| pbsv_dp                              | "Read depth at this position for this sample" ('DP' in VCF FORMAT)                                          |
| pbsv_sac                             | "Number of reads on the forward and reverse strand supporting each allele including reference" ('SAC' in VCF FORMAT) |
| pbsv_cn                              | "Copy number genotype for imprecise events" ('CN' in VCF FORMAT)                                            |
: {tbl-colwidths="[30,55,15]"}

</div>


### Sniffles2 Headers

A Sniffles2 TSV includes all of the common headers. The descriptions were taken from Sniffles2 2.0.6.

<div class="table">

| Header                               | Description                                                                                               |
| ------------------------------------ | --------------------------------------------------------------------------------------------------------- |
| sniffles2_precise                    | "Structural variation with precise breakpoints" ('PRECISE' in VCF INFO)                                   |
| sniffles2_svlen                      | "Length of structural variation" ('SVLEN' in VCF INFO)                                                    |
| sniffles2_svtype                     | "Type of structural variation" ('SVTYPE' in VCF INFO)                                                     |
| sniffles2_chr2                       | "Mate chromsome for BND SVs" ('CHR2' in VCF INFO)                                                         |
| sniffles2_support                    | "Number of reads supporting the structural variation" ('SUPPORT' in VCF INFO)                             |
| sniffles2_support_inline             | "Number of reads supporting an INS/DEL SV (non-split events only)" ('SUPPORT_INLINE' in VCF INFO)         |
| sniffles2_support_long               | "Number of soft-clipped reads putatively supporting the long insertion SV" ('SUPPORT_LONG' in VCF INFO)   |
| sniffles2_end                        | "End position of structural variation" ('END' in VCF INFO)                                                |
| sniffles2_stdev_pos                  | "Standard deviation of structural variation start position" ('STDEV_POS' in VCF INFO)                     |
| sniffles2_stdev_len                  | "Standard deviation of structural variation length" ('STDEV_LEN' in VCF INFO)                             |
| sniffles2_coverage                   | "Coverages near upstream, start, center, end, downstream of structural variation" ('COVERAGE' in VCF INFO) |
| sniffles2_strand                     | "Strands of supporting reads for structural variant" ('STRAND' in VCF INFO)                               |
| sniffles2_ac                         | "Allele count, summed up over all samples" ('AC' in VCF INFO)                                             |
| sniffles2_supp_vec                   | "List of read support for all samples" ('SUPP_VEC' in VCF INFO)                                           |
| sniffles2_consensus_support          | "Number of reads that support the generated insertion (INS) consensus sequence" ('CONSENSUS_SUPPORT' in VCF INFO) |
| sniffles2_rnames                     | "Names of supporting reads (if enabled with --output-rnames)" ('RNAMES' in VCF INFO)                      |
| sniffles2_af                         | "Allele Frequency" ('AF' in VCF INFO)                                                                     |
| sniffles2_nm                         | "Mean number of query alignment length adjusted mismatches of supporting reads" ('NM' in VCF INFO)        |
| sniffles2_phase                      | "Phasing information derived from supporting reads, represented as list of: HAPLOTYPE,PHASESET,HAPLOTYPE_SUPPORT,PHASESET_SUPPORT,HAPLOTYPE_FILTER,PHASESET_FILTER" ('PHASE' in VCF INFO) |
| sniffles2_gt                         | "Genotype" ('GT' in VCF FORMAT)                                                                           |
| sniffles2_gq                         | "Genotype quality" ('GQ' in VCF FORMAT)                                                                   |
| sniffles2_dr                         | "Number of reference reads" ('DR' in VCF FORMAT)                                                          |
| sniffles2_dv                         | "Number of variant reads" ('DV' in VCF FORMAT)                                                            |
| sniffles2_id                         | "Individual sample SV ID for multi-sample output" ('ID' in VCF FORMAT)                                    |
: {tbl-colwidths="[30,55,15]"}

</div>

### Strelka2-Germline Headers

A Strelka2-Germline TSV includes all of the common headers. The descriptions were taken from Strelka 2.9.10.

<div class="table">

| Header                               | Description                                                                                               |
| ------------------------------------ | --------------------------------------------------------------------------------------------------------- |
| strelka2-germline_end                | "End position of the region described in this record" ('END' in VCF INFO)                                 |
| strelka2-germline_blockavg_min30p3a  | "Non-variant multi-site block. Non-variant blocks are defined independently for each sample. All sites in such a block are constrained to be non-variant, have the same filter value, and have sample values {GQX,DP,DPF} in range [x,y], y <= max(x+3,(x*1.3))" ('BLOCKAVG_min30p3a' in VCF INFO)           |
| strelka2-germline_snvhpol            | "SNV contextual homopolymer length" ('SNVHPOL' in VCF INFO)                                               |
| strelka2-germline_cigar              | "CIGAR alignment for each alternate indel allele" ('CIGAR' in VCF INFO)                                   |
| strelka2-germline_ru                 | "Smallest repeating sequence unit extended or contracted in the indel allele relative to the reference. RUs are not reported if longer than 20 bases" ('RU' in VCF INFO) |
| strelka2-germline_refrep             | "Number of times RU is repeated in reference" ('REFREP' in VCF INFO)                                      |
| strelka2-germline_idrep              | "Number of times RU is repeated in indel allele" ('IDREP' in VCF INFO)                                    |
| strelka2-germline_mq                 | "RMS of mapping quality" ('MQ' in VCF INFO)                                                               |
| strelka2-germline_gt                 | "Genotype" ('GT' in VCF FORMAT)                                                                             |
| strelka2-germline_gq                 | "Genotype quality" ('GQ' in VCF FORMAT)                                                                     |
| strelka2-germline_gqx                | "Empirically calibrated genotype quality score for variant sites, otherwise minimum of {Genotype quality assuming variant position,Genotype quality assuming non-variant position}" ('GQX' in VCF FORMAT) |
| strelka2-germline_dp                 | "Filtered basecall depth used for site genotyping. In a non-variant multi-site block this value represents the average of all sites in the block" ('DP' in VCF FORMAT) |
| strelka2-germline_dpf                | "Basecalls filtered from input prior to site genotyping. In a non-variant multi-site block this value represents the average of all sites in the block" ('DPF' in VCF FORMAT) |
| strelka2-germline_min_dp             | "Minimum filtered basecall depth used for site genotyping within a non-variant multi-site block" ('MIN_DP' in VCF FORMAT) |
| strelka2-germline_ad                 | "Allelic depths for the ref and alt alleles in the order listed. For indels this value only includes reads which confidently support each allele (posterior prob 0.51 or higher that read contains indicated allele vs all other intersecting indel alleles)" ('AD' in VCF FORMAT) |
| strelka2-germline_adf                | "Allelic depths on the forward strand" ('ADF' in VCF FORMAT) |
| strelka2-germline_adr                | "Allelic depths on the reverse strand" ('ADR' in VCF FORMAT) |
| strelka2-germline_ft                 | "Sample filter, 'PASS' indicates that all filters have passed for this sample" ('FT' in VCF FORMAT) |
| strelka2-germline_dpi                | "Read depth associated with indel, taken from the site preceding the indel" ('DPI' in VCF FORMAT) |
| strelka2-germline_pl                 | "Normalized, Phred-scaled likelihoods for genotypes as defined in the VCF specification" ('PL' in VCF FORMAT) |
| strelka2-germline_ps                 | "Phase set identifier" ('PS' in VCF FORMAT) |
| strelka2-germline_sb                 | "Sample site strand bias" ('SB' in VCF FORMAT) |
: {tbl-colwidths="[30,55,15]"}

</div>

### Strelka2-Somatic Headers

In addition to the following Strelka2 (somatic mode) specific headers, a Strelka2-Somatic VCF file converted to a TSV file includes all of the above common headers. The descriptions were taken from Strelka 2.9.10.

<div class="table">

| Header                               | Description                                                                                               |
| ------------------------------------ | --------------------------------------------------------------------------------------------------------- |
| strelka2-somatic_qss                 | "Quality score for any somatic variant for the ALT allele to be present at a significantly different frequency in the tumor and normal" ('QSS' in SNV VCF INFO) |
| strelka2-somatic_tqss                | "Data tier used to compute QSS" ('TQSS' in SNV VCF INFO) |
| strelka2-somatic_nt                  | "Genotype of the normal in all data tiers, as used to classify somatic variants. One of {ref,het,hom,conflict}" ('NT' in SNV and INDEL VCF INFO) |
| strelka2-somatic_qss_nt              | "Quality score reflecting the joint probability of a somatic variant and NT ('QSS_NT' in SNV VCF INFO) |
| strelka2-somatic_tqss_nt             | "Data tier used to compute QSS_NT ('TQSS_NT' in SNV VCF INFO) |
| strelka2-somatic_sgt                 | "Most likely somatic genotype excluding normal noise states ('SGT' in SNV and INDEL VCF INFO) |
| strelka2-somatic_somatic             | "Somatic mutation" ('SOMATIC' in SNV VCF INFO) |
| strelka2-somatic_dp                  | "Combined depth across samples ('DP' in SNV VCF INFO)" |
| strelak2-somatic_mq                  | "RMS Mapping Quality ('MQ' in SNV and INDEL VCF INFO) |
| strelka2-somatic_mq0                 | "Total Mapping Quality Zero Reads ('MQ0' in SNV and INDEL VCF INFO)" |
| strelak2-somatic_readposranksum      | "Z-score from Wilcoxon rank sum test of Alt Vs. Ref read-position in the tumor" ('ReadPosRankSum' in SNV VCF INFO) | Strelak2 (somatic) |
| strelka2-somatic_snvsb               | "Somatic SNV site strand bias" ('SNVSB' in SNV VCF INFO) |
| strelka2-somatic_pnoise              | "Fraction of panel containing non-reference noise at this site" ('PNOISE' in SNV VCF INFO) |
| strelka2-somatic_pnoise2             | "Fraction of panel containing more than one non-reference noise obs at this site" ('PNOISE2' in SNV VCF INFO) |
| strelka2-somatic_somaticevs          | "Somatic Empirical Variant Score (EVS) expressing the phred-scaled probability of the call being a false positive observation" ('SomaticEVS' in SNV and INDEL VCF INFO) |
| strelka2-somatic_qsi                 | "Quality score for any somatic variant, ie. for the ALT haplotype to be present at a significantly different frequency in the tumor and normal" ('QSI' in INDEL VCF INFO) |
| strelka2-somatic_tqsi                | "Data tier used to compute QSI" ('TQSI' in INDEL VCF INFO) |
| strelka2-somatic_qsi_nt              | "Quality score reflecting the joint probability of a somatic variant and NT" ('QSI_NT' in INDEL VCF INFO) |
| strelka2-somatic_tqsi_nt             | "Data tier used to compute QSI_NT" ('TQSI_NT' in INDEL VCF INFO) |
| strelka2-somatic_ru                  | "Smallest repeating sequence unit in inserted or deleted sequence" ('RU' in INDEL VCF INFO) |
| strelka2-somatic_rc                  | "Number of times RU repeats in the reference allele" ('RC' in INDEL VCF INFO) |
| strelka2-somatic_ic                  | "Number of times RU repeats in the indel allele" ('IC' in INDEL VCF INFO) |
| strelka2-somatic_ihp                 | "Largest reference interrupted homopolymer length intersecting with the indel" ('IHP' in INDEL VCF INFO) |
| strelka2-somatic_overlap             | "Somatic indel possibly overlaps a second indel" ('OVERLAP' in INDEL VCF INFO) |
| strelka2-somatic_tumor_fdp           | "Number of basecalls filtered from original read depth for tier1" ('FDP' in SNV VCF FORMAT) |
| strelka2-somatic_normal_fdp          | "Number of basecalls filtered from original read depth for tier1" ('FDP' in SNV VCF FORMAT) |
| strelka2-somatic_tumor_sdp           | "Number of reads with deletions spanning this site at tier1" ('SDP' in SNV VCF FORMAT) |
| strelka2-somatic_normal_sdp          | "Number of reads with deletions spanning this site at tier1" ('SDP' in SNV VCF FORMAT) |
| strelka2-somatic_tumor_subdp         | "Number of reads below tier1 mapping quality threshold aligned across this site" ('SUBDP' in SNV VCF FORMAT) |
| strelka2-somatic_normal_subdp        | "Number of reads below tier1 mapping quality threshold aligned across this site" ('SUBDP' in SNV VCF FORMAT) |
| strelka2-somatic_tumor_au            | "Number of 'A' alleles used in tiers 1,2" ('AU' in SNV VCF FORMAT) |
| strelka2-somatic_normal_au           | "Number of 'A' alleles used in tiers 1,2" ('AU' in SNV VCF FORMAT) |
| strelka2-somatic_tumor_cu            | "Number of 'C' alleles used in tiers 1,2" ('CU' in SNV VCF FORMAT) |
| strelka2-somatic_normal_cu           | "Number of 'C' alleles used in tiers 1,2" ('CU' in SNV VCF FORMAT) |
| strelka2-somatic_tumor_gu            | "Number of 'G' alleles used in tiers 1,2" ('GU' in SNV VCF FORMAT) |
| strelka2-somatic_normal_gu           | "Number of 'G' alleles used in tiers 1,2" ('GU' in SNV VCF FORMAT) |
| strelka2-somatic_tumor_tu            | "Number of 'T' alleles used in tiers 1,2" ('TU' in SNV VCF FORMAT) |
| strelka2-somatic_normal_tu           | "Number of 'T' alleles used in tiers 1,2" ('TU' in SNV VCF FORMAT) |
| strelka2-somatic_tumor_dp            | "Read depth for tier1" ('DP' in SNV and INDEL VCF FORMAT) |
| strelka2-somatic_normal_dp           | "Read depth for tier1" ('DP' in SNV and INDEL VCF FORMAT) |
| strelka2-somatic_tumor_dp2           | "Read depth for tier2" ('DP2' in INDEL VCF FORMAT) |
| strelka2-somatic_normal_dp2          | "Read depth for tier2" ('DP2' in INDEL VCF FORMAT) |
| strelka2-somatic_tumor_tar           | "Reads strongly supporting alternate allele for tiers 1,2" ('TAR' in INDEL VCF FORMAT) |
| strelka2-somatic_normal_tar          | "Reads strongly supporting alternate allele for tiers 1,2" ('TAR' in INDEL VCF FORMAT) |
| strelka2-somatic_tumor_tir           | "Reads strongly supporting indel allele for tiers 1,2" ('TIR' in INDEL VCF FORMAT) |
| strelka2-somatic_normal_tir          | "Reads strongly supporting indel allele for tiers 1,2" ('TIR' in INDEL VCF FORMAT) |
| strelka2-somatic_tumor_tor           | "Other reads (weak support or insufficient indel breakpoint overlap) for tiers 1,2" ('TOR' in INDEL VCF FORMAT) |
| strelka2-somatic_normal_tor          | "Other reads (weak support or insufficient indel breakpoint overlap) for tiers 1,2" ('TOR' in INDEL VCF FORMAT) |
| strelka2-somatic_tumor_dp50          | "Average tier1 read depth within 50 bases" ('DP50' in INDEL VCF FORMAT) |
| strelka2-somatic_normal_dp50         | "Average tier1 read depth within 50 bases" ('DP50' in INDEL VCF FORMAT) |
| strelka2-somatic_tumor_fdp50         | "Average tier1 number of basecalls filtered from original read depth within 50 bases" ('FDP50' in INDEL VCF FORMAT) |
| strelka2-somatic_normal_fdp50        | "Average tier1 number of basecalls filtered from original read depth within 50 bases" ('FDP50' in INDEL VCF FORMAT) |
| strelka2-somatic_tumor_subdp50       | "Average number of reads below tier1 mapping quality threshold aligned across sites within 50 bases" ('SUBDP50' in INDEL VCF FORMAT) |
| strelka2-somatic_normal_subdp50      | "Average number of reads below tier1 mapping quality threshold aligned across sites within 50 bases" ('SUBDP50' in INDEL VCF FORMAT) |
| strelka2-somatic_tumor_bcn50         | "Fraction of filtered reads within 50 bases of the indel" ('BCN50' in INDEL VCF FORMAT) |
| strelka2-somatic_normal_bcn50        | "Fraction of filtered reads within 50 bases of the indel" ('BCN50' in INDEL VCF FORMAT) |
: {tbl-colwidths="[30,55,15]"}

</div>

