name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        activate-environment: test-env
        python-version: "3.10"

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        # Remove tmp files
        sudo rm -rf /tmp/*

        # Install conda packages
        conda env list
        conda info
        conda config --add channels defaults
        conda config --add channels bioconda
        conda config --add channels conda-forge
        conda config --set channel_priority strict
        conda install -c conda-forge mamba
        conda install rust
        mamba install pandas
        mamba install pyensembl=2.1.0
        mamba install pysam
        mamba install networkx
        mamba install matplotlib
        mamba install pylint
        mamba install coveralls
        mamba install pytest
        mamba install pytest-cov

        # Install pyensembl data
        pyensembl install --release 95 --species human --custom-mirror https://github.com/openvax/ensembl-data/releases/download/GRCh38.95/
  
        # Install exacto
        pip install . --verbose
      env:
        PYENSEMBL_CACHE_DIR: $HOME/cache/
        CARGO_TARGET_DIR: $HOME/cache/cargo/
        CARGO_BUILD_TARGET_DIR: $HOME/cache/cargo/

    - name: Run linter
      shell: bash -l {0}
      run: |
        chmod +x lint.sh
        bash lint.sh

    - name: Run unit tests
      shell: bash -l {0}
      run: |
        chmod +x unittest.sh
        bash unittest.sh
      env:
        PYENSEMBL_CACHE_DIR: $HOME/cache/